language: java

branches:
  except:
      #- /^(?i:feature)-.*$/
      #- /^(?i:release)-.*$/

jdk:
  - oraclejdk8
  
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
    slack: openbase-org:vGz7LO4CvGoGMneYkEm3ON7E
    on_failure: change
    on_success: change	
